import {test,expect} from 'bun:test';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {spawnSync} from 'node:child_process';
import {documents_from,validate_research,validate_review} from '../dist/src/research.mjs';import {validate_plan,official_url_QMARK_,links_from} from '../dist/src/search.mjs';import {snapshot,post} from './fixture.mjs';
const incident={id:'official-fixture',updated_at:'2026-09-25T00:00:00Z',name:'Codex requests failed',status:'resolved',impact:'minor',components:[{name:'Codex'}],incident_updates:[{body:'A fix was deployed for affected Codex requests.'}]};
const sources=[{name:'status',ok:true,body:JSON.stringify({incidents:[incident,{...incident,id:'old',updated_at:'2026-01-01T00:00:00Z'},{...incident,id:'future',updated_at:'2027-01-01T00:00:00Z'}]})},{name:'news',ok:true,body:'<rss><channel><item><title><![CDATA[Codex new tools]]></title><link>https://openai.com/index/codex-tools/</link><pubDate>Wed, 24 Sep 2026 00:00:00 GMT</pubDate><description><![CDATA[<p>New tools for Codex</p>]]></description></item></channel></rss>'}];
test('native research selects recent official Codex incidents and releases, excludes future/old records and never sends raw pages',()=>{const docs=documents_from(snapshot({sources}));expect(docs).toHaveLength(2);expect(docs[0]).toMatchObject({type:'incident',status:'resolved',impact:'minor'});expect(docs[1].text).toContain('Codex new tools');expect(docs[1].url).toBe('https://openai.com/index/codex-tools/');expect(docs.every(d=>d.text.length<=1200)).toBe(true);expect(documents_from(snapshot({sources:[{name:'status',ok:true,body:'broken'}]}))).toEqual([]);});
test('structured research and review accept only grounded quotations, bounded enums and traceable links',()=>{const input={posts:[post(25,'Codex limits reset for affected Pro accounts.'),post(25,'A fix is now deployed for affected accounts.',{id:'reply'})],documents:[]};const v={facts:[{sourceId:'post-25',quote:'Codex limits reset',kind:'reset',scope:'subset',status:'resolved',impact:'minor'}],links:[{fromId:'post-25',fromQuote:'Codex limits reset',toId:'reply',toQuote:'A fix is now deployed',relation:'clarifies'}]};expect(validate_research(v,input).facts[0].scope).toBe('subset');expect(()=>validate_research({...v,facts:[{...v.facts[0],sourceId:'invented'}]},input)).toThrow();expect(()=>validate_research({...v,links:[{...v.links[0],toQuote:'fake quote'}]},input)).toThrow();expect(()=>validate_review({accept:true,reason:'banked',citations:[{sourceId:'post-25',quote:'Codex limits reset'}]},input)).toThrow();expect(validate_review({accept:false,reason:'unsupported-scope',citations:[{sourceId:'post-25',quote:'Codex limits reset'}]},input).accept).toBe(false);});
test('AI search can only choose two bounded business queries; URLs and identities are never fetch targets',()=>{expect(validate_plan({queries:[{engine:'google',query:'Codex Pro quota compensation'}]}).queries).toHaveLength(1);for(const query of ['api key Codex','Codex https://localhost/private','Codex site:evil.invalid','Codex sk-123456789abcdef'])expect(()=>validate_plan({queries:[{engine:'google',query}]})).toThrow();expect(()=>validate_plan({queries:[{engine:'shell',query:'Codex reset'}]})).toThrow();});
test('actual Google JS shell and Baidu script redirect are unavailable, never true empty results',()=>{
 expect(()=>links_from('<title>Google Search</title><style>table,div{display:none}</style><script>window.google={}</script>','google')).toThrow('脚本');
 expect(()=>links_from('<script>location.replace(location.href.replace("https://", "http://"));</script>','baidu')).toThrow('脚本');
 expect(links_from('<html><title>Codex search results</title><p>No matches</p></html>','google')).toEqual([]);
});
test('customer stories are excluded and grounded historic context is available to research',()=>{
 const item=(title,url)=>`<item><title>${title}</title><link>${url}</link><pubDate>Wed, 24 Sep 2026 00:00:00 GMT</pubDate><description>Codex usage and new updates</description></item>`;
 const docs=documents_from(snapshot({sources:[{name:'news',ok:true,body:`<rss>${item('Chatham scales its capital markets expertise with OpenAI','https://openai.com/index/chatham/')}${item('Are you a Codex Original?','https://openai.com/form/codex-original/')}${item('DevDay 2026 Recap','https://openai.com/index/devday-2026/')}</rss>`}]}));
 expect(docs).toHaveLength(1);expect(docs[0].text).toContain('DevDay');
 expect(validate_research({facts:[{sourceId:'historic',quote:'Reset all propagated.',kind:'reset',scope:'global',status:'resolved',impact:'unknown'}],links:[]},
   {posts:[],documents:[],lastGlobal:{id:'historic',text:'Reset all propagated. Enjoy.',provenance:'primary'}}).facts[0].sourceId).toBe('historic');
});
async function run(code,features='signals,search,research,forecast,review,brief'){const dir=await mkdtemp(join(tmpdir(),'tibo-research-'));try{const r=spawnSync(process.execPath,['--eval',code],{env:{...process.env,TIBO_STATE_DIR:dir,TIBO_AI_FEATURES:features,DEEPSEEK_API_KEY:'fixture-research-key'},encoding:'utf8',timeout:6000});expect(r.status).toBe(0);expect(r.stderr).toBe('');return JSON.parse(r.stdout);}finally{await rm(dir,{recursive:true,force:true});}}
const searchModule=JSON.stringify(resolve('dist/src/search.mjs')),ai=JSON.stringify(resolve('dist/src/ai.mjs')),engine=JSON.stringify(resolve('dist/src/engine.mjs'));
test('search executes Google and Baidu, reads only official pages, rejects private redirects, then reuses page and query cache',async()=>{const r=await run(`let urls=[];globalThis.fetch=async(u,o)=>{urls.push(String(u));if(String(u).includes('google.com/search'))return new Response('<a href="/url?q=https%3A%2F%2Fhelp.openai.com%2Fen%2Farticle">Codex docs</a><a href="http://127.0.0.1/private">private</a>');if(String(u).includes('baidu.com/s?'))return new Response('<a href="https://www.baidu.com/link?url=fixture">Codex</a>');if(String(u).includes('baidu.com/link?'))return new Response('',{status:302,headers:{location:'http://127.0.0.1/private'}});return new Response('<main>Codex usage limits depend on your account plan. Limits are documented here, including manual resets and eligible usage policies for paid accounts.</main>')};const {run_search}=await import(${searchModule});const plan={queries:[{engine:'google',query:'Codex usage limits'},{engine:'baidu',query:'Codex usage limits'}]};const a=await run_search(plan),n=urls.length,b=await run_search(plan);console.log(JSON.stringify({a,b,urls,n}));`);expect(r.a.documents).toHaveLength(1);expect(r.a.documents[0].at).toBeNull();expect(r.a.documents[0].provenance).toBe('official-page');expect(r.urls.some(u=>u.includes('127.0.0.1'))).toBe(false);expect(r.b.engines.every(x=>x.cached)).toBe(true);expect(r.urls.length-r.n).toBe(1);/* Failed Baidu resolution is bounded; official page itself is cached. */});
test('search failure is cached and no CAPTCHA text becomes evidence',async()=>{const r=await run(`let calls=0;globalThis.fetch=async()=>{calls++;return new Response('<title>百度安全验证</title><p>Codex reset all</p>')};const {run_search}=await import(${searchModule});const p={queries:[{engine:'baidu',query:'Codex reset'}]};const a=await run_search(p),b=await run_search(p);console.log(JSON.stringify({a,b,calls}));`);expect(r.calls).toBe(1);expect(r.a.documents).toEqual([]);expect(r.a.engines[0].state).toBe('unavailable');expect(r.b.engines[0].cached).toBe(true);});
const active=snapshot({posts:[post(25,'Global reset landing tomorrow for all users.')]});
async function pipeline(accept){return run(`let prompts=[];globalThis.fetch=async(u,o)=>{const body=JSON.parse(o.body);prompts.push(body);let value;if(body.messages[0].content.includes('facts='))value={facts:[{sourceId:'post-25',quote:'Global reset landing tomorrow',kind:'reset',scope:'global',status:'planned',impact:'unknown'}],links:[]};else if(body.messages[0].content.includes('检查proposal'))value={accept:${accept},reason:${JSON.stringify(accept?'consistent':'weak-evidence')},citations:[{sourceId:'post-25',quote:'Global reset landing tomorrow'}]};else value={p24:90,p48:95,reason:'待兑现新承诺',citations:[{postId:'post-25',quote:'Global reset landing tomorrow for all users.'}]};return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify(value)}}],usage:{prompt_tokens:12,completion_tokens:8}}))};const {judge}=await import(${engine});const {enhance}=await import(${ai});const initial=judge(${JSON.stringify(active)}),base={p24:initial.forecast.p24,p48:initial.forecast.p48};const r=await enhance(initial);const before=prompts.length;await enhance(judge(${JSON.stringify(active)}));const {ai_status}=await import(${JSON.stringify(resolve('dist/src/ai-runtime.mjs'))});console.log(JSON.stringify({base,p24:r.forecast.p24,weight:r.ai.weight,features:r.ai.features,prompts,cachedExtraCalls:prompts.length-before,usage:(await ai_status()).usage,clock:r.signals.lastGlobal.at}));`,'research,forecast,review');}
test('research fields feed probability model and grounded review rejection preserves the core; every repeated task caches',async()=>{const r=await pipeline(false);expect(r.features.research.state).toBe('ok');expect(r.prompts).toHaveLength(3);const input=JSON.parse(r.prompts[1].messages[1].content);expect(input.research.facts[0].scope).toBe('global');expect(r.p24).toBe(r.base.p24);expect(r.weight).toBe(0);expect(r.cachedExtraCalls).toBe(0);expect(r.usage.research.calls).toBe(1);expect(r.usage.review.completionTokens).toBe(8);expect(r.clock).toBe('2026-09-24T00:00:00Z');expect(r.prompts.map(x=>x.max_tokens)).toEqual([1400,500,320]);});
test('review acceptance allows bounded blending; review unavailability cannot silently accept a large probability change',async()=>{const r=await pipeline(true);expect(r.p24).toBe(Math.round(.8*r.base.p24+.2*90));expect(r.weight).toBe(.2);const failed=await run(`let calls=0;globalThis.fetch=async()=>{calls++;if(calls===2)return new Response('',{status:500});return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({p24:90,p48:95,reason:'新承诺',citations:[{postId:'post-25',quote:'Global reset landing tomorrow for all users.'}]})}}]}))};const {judge}=await import(${engine});const {enhance}=await import(${ai});const r=judge(${JSON.stringify(active)}),p=r.forecast.p24;await enhance(r);console.log(JSON.stringify({p,actual:r.forecast.p24,review:r.ai.features.review.state}));`,'forecast,review');expect(failed.actual).toBe(failed.p);expect(failed.review).toBe('fallback');});
test('without new signals AI does not ask for probabilities, review, search or prose and repeated classification costs zero',async()=>{const r=await run(`let calls=0;globalThis.fetch=async()=>{calls++;return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({items:[]})}}]}))};const {judge}=await import(${engine});const {enhance}=await import(${ai});const r=await enhance(judge(${JSON.stringify(snapshot())}));await enhance(judge(${JSON.stringify(snapshot())}));console.log(JSON.stringify({calls,features:r.ai.features}));`);expect(r.calls).toBe(1);for(const f of ['search','research','forecast','review','brief'])expect(r.features[f].state).toBe('skipped');});
test('research linked output can be revalidated on cache hits; input budget and truncated output token accounting are explicit',async()=>{const r=await run(`let calls=0;globalThis.fetch=async()=>{calls++;return new Response(JSON.stringify({choices:[{finish_reason:'length',message:{content:'{}'}}],usage:{prompt_tokens:9,completion_tokens:220}}))};const {ai_call,ai_status}=await import(${JSON.stringify(resolve('dist/src/ai-runtime.mjs'))});const oversized=await ai_call('search',{instruction:'JSON',evidence:{text:'x'.repeat(24001)}},v=>v);const truncated=await ai_call('search',{instruction:'JSON',evidence:{}},v=>v);const {validate_research}=await import(${JSON.stringify(resolve('dist/src/research.mjs'))});const input={posts:[{id:'a',text:'A new reset is planned.'},{id:'b',text:'The reset is complete.'}]},value={facts:[],links:[{fromId:'a',fromQuote:'A new reset is planned.',toId:'b',toQuote:'The reset is complete.',relation:'fulfills'}]};const one=validate_research(value,input),two=validate_research(one,input);console.log(JSON.stringify({oversized,truncated,calls,usage:(await ai_status()).usage,same:JSON.stringify(one)===JSON.stringify(two)}));`);expect(r.oversized.state).toBe('skipped');expect(r.calls).toBe(1);expect(r.truncated.state).toBe('fallback');expect(r.usage.search).toMatchObject({calls:1,promptTokens:9,completionTokens:220});expect(r.same).toBe(true);});
