import {test,expect} from 'bun:test';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {spawnSync} from 'node:child_process';
import {validate_wish,local_wish} from '../dist/src/wish.mjs';
const root=resolve('dist/src');
async function trial(code){const dir=await mkdtemp(join(tmpdir(),'tibo-wish-'));try{const r=spawnSync(process.execPath,['--eval',code],{env:{...process.env,TIBO_CONFIG_FILE:'/dev/null',TIBO_STATE_DIR:dir,DEEPSEEK_API_KEY:'fixture-key',TIBO_AI_FEATURES:'wish'},encoding:'utf8',timeout:7000});expect(r.status,r.stderr).toBe(0);return JSON.parse(r.stdout);}finally{await rm(dir,{recursive:true,force:true});}}
const setup=`const {pray,identity_key}=await import(${JSON.stringify(root+'/pray.mjs')});const {read_state,write_state}=await import(${JSON.stringify(root+'/state.mjs')});const ctx={transport:'lark',actor:'private-owner',scope:'private-room',authenticated:true};`;
test('wish requires token, a divine blessing and private-free text rather than a real quota operation',()=>{
 for(let i=0;i<4;i++)expect(validate_wish({wish:local_wish(i)}).wish).toContain('token');
 const repaired=validate_wish({wish:'善信，本神愿汝上下文稳固，Agent童子靠谱，CI天灯长明。'});expect(repaired.wish).toContain('token');expect(validate_wish(repaired)).toEqual(repaired);
 for(const v of [null,{}, {wish:'愿你好运'}, {wish:'善信，本神赐汝满格token，现在已为你增加额度'}, {wish:'善信，本神愿汝token不枯，访问https://example.com领取额度'}, {wish:local_wish(0),shell:'run'}, {wish:'善信，本神愿汝token充沛，Claude跪拜，测试皆绿'}])expect(()=>validate_wish(v)).toThrow();
});
test('AI sees only a bounded scene, follows durable prayer accounting and replays without regeneration',async()=>{
 const r=await trial(`let body,calls=0,storedBefore;const generated='善信，本神愿汝token不枯，CI天灯长明，Bug心魔退散。';globalThis.fetch=async(url,o)=>{calls++;body=JSON.parse(o.body);storedBefore=await read_state(identity_key);if(storedBefore.offers!==1)throw Error('not committed');if(await Bun.file(process.env.TIBO_STATE_DIR+'/'+identity_key+'.json.lock/owner.json').exists())throw Error('identity lock held');return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({wish:generated})}}]}))};${setup}const first=await pray({action:'offer'},{...ctx,requestId:'same-event'});const repeat=await pray({action:'offer'},{...ctx,requestId:'same-event'});await pray({action:'me'},ctx);await pray({action:'board'},ctx);await pray({action:'stats'},ctx);console.log(JSON.stringify({first,repeat,calls,body,storedBefore,after:await read_state(identity_key)}));`);
 expect(r.calls).toBe(1);expect(r.first).toEqual(r.repeat);expect(r.first.text).toContain('CI天灯');expect(Object.keys(r.first).sort()).toEqual(['ok','text']);
 const input=JSON.parse(r.body.messages[1].content);expect(input.scene).toBe('first');expect(Object.keys(input).sort()).toEqual(['scene','variant']);expect(JSON.stringify(r.body)).not.toMatch(/private-owner|private-room|fixture-key/);expect(r.body.max_tokens).toBe(160);expect(r.body.temperature).toBe(1.2);
 expect(r.storedBefore.offers).toBe(1);expect(r.storedBefore.scopes[0].state.receipts[0].text).toContain('token');expect(r.after.offers).toBe(1);expect(r.after.scopes[0].state.receipts[0].text).toBe(r.first.text);
});
test('disabled, no-ai and provider cooling keep local blessings with zero network calls',async()=>{
 const r=await trial(`let calls=0;globalThis.fetch=async()=>{calls++;throw Error('must not fetch')};${setup}const {config}=await import(${JSON.stringify(root+'/ai-runtime.mjs')});const {execute_query,resolve_query}=await import(${JSON.stringify(root+'/commands.mjs')});const a=await execute_query(await resolve_query('pray --no-ai',{}, {humanInput:true}),{humanInput:true,noAi:true,context:ctx});process.env.TIBO_AI_FEATURES='';const b=await pray({action:'offer'},{...ctx,requestId:'disabled'});process.env.TIBO_AI_FEATURES='wish';await write_state('ai',{identity:config().identity,provider:{until:Date.now()+60000},features:{},cache:[]});const c=await pray({action:'offer'},{...ctx,requestId:'blocked'});console.log(JSON.stringify({calls,a,b,c,count:(await read_state(identity_key)).offers}));`);
 expect(r.calls).toBe(0);expect(r.count).toBe(3);for(const v of [r.a,r.b,r.c]){expect(v.ok).toBe(true);expect(v.text).toContain('token');expect(v.text).not.toContain('出了问题');}
});
test('slow AI aborts within the prayer budget, leaves a durable fallback and never counts a replay again',async()=>{
 const r=await trial(`let calls=0;globalThis.fetch=async(url,o)=>{calls++;return new Promise((resolve,reject)=>o.signal.addEventListener('abort',()=>reject(o.signal.reason),{once:true}))};${setup}const started=Date.now();const a=await pray({action:'offer'},{...ctx,requestId:'timeout'});const elapsed=Date.now()-started;const b=await pray({action:'offer'},{...ctx,requestId:'timeout'});console.log(JSON.stringify({a,b,calls,elapsed,root:await read_state(identity_key)}));`);
 expect(r.calls).toBe(1);expect(r.elapsed).toBeLessThan(2300);expect(r.a).toEqual(r.b);expect(r.a.text).toContain('token');expect(r.root.offers).toBe(1);expect(r.root.merit).toBe(1);
});
test('invalid wish output cools only its own task and preserves prayer accounting',async()=>{
 const r=await trial(`let calls=0,answerMode=false;globalThis.fetch=async()=>{calls++;return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:answerMode?'{"text":"still works"}':'{"wish":"已重置token额度"}'}}]}))};${setup}for(let i=0;i<3;i++)await pray({action:'offer'},{...ctx,requestId:'bad-'+i});const {ai_status,ai_call}=await import(${JSON.stringify(root+'/ai-runtime.mjs')});const status=await ai_status();const badCalls=calls;answerMode=true;process.env.TIBO_AI_FEATURES='wish,answer';const other=await ai_call('answer',{instruction:'answer',evidence:{}},v=>v);console.log(JSON.stringify({calls:badCalls,status,other,root:await read_state(identity_key)}));`);
 expect(r.calls).toBe(2);expect(r.status.circuit.features.wish.until).toBeGreaterThan(Date.now());expect(r.status.circuit.provider.until).toBe(0);expect(r.other.state).toBe('ok');expect(r.root.offers).toBe(3);for(const receipt of r.root.scopes[0].state.receipts)expect(receipt.text).toContain('🪄');
});
