import {test,expect} from 'bun:test';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {spawnSync} from 'node:child_process';
import {prepare_celebration,emoji_art,validate_celebration_wish} from '../../dist/src/prayer/celebration.mjs';
import {points,names} from '../../dist/src/prayer/festivals.mjs';
const root=resolve('dist');
const setup=`const ctx={transport:'lark',account:'private-account',scope:'oc_room',actor:'ou_owner',authenticated:true,conversationType:'group'};const {pray,record_pray,identity_key}=await import(${JSON.stringify(root+'/src/prayer/pray.mjs')});const {read_state,write_state}=await import(${JSON.stringify(root+'/src/platform/state.mjs')});const {deliver,delivery_key}=await import(${JSON.stringify(root+'/adapters/lark/service.mjs')});const {finish_celebration,celebration_key}=await import(${JSON.stringify(root+'/adapters/lark/celebration-delivery.mjs')});const {prepare_celebration,enrich_celebration}=await import(${JSON.stringify(root+'/src/prayer/celebration.mjs')});const {write_pending}=await import(${JSON.stringify(root+'/adapters/lark/inbox-store.mjs')});const {create_inbox}=await import(${JSON.stringify(root+'/adapters/lark/inbox.mjs')});const seed=async n=>{for(let i=0;i<n;i++)await record_pray({action:'offer'},{...ctx,requestId:'seed'+i},{silent:true})};const state=async()=> (await read_state(identity_key)).scopes[0].state;`;
async function trial(code,features=''){const dir=await mkdtemp(join(tmpdir(),'tibo-celebration-'));try{const r=spawnSync(process.execPath,['--eval',"let testFetch;globalThis.fetch=(...args)=>{if(!testFetch)throw Error('unexpected network');return testFetch(...args)};"+setup+code.replaceAll('globalThis.fetch=','testFetch=')],{env:{...process.env,TIBO_CONFIG_FILE:'/dev/null',TIBO_STATE_DIR:dir,TIBO_AI_FEATURES:features,DEEPSEEK_API_KEY:'fixture-key',TIBO_LARK_APP_ID:'fixture',TIBO_LARK_DOMAIN:'lark'},encoding:'utf8',timeout:12000});expect(r.status,r.stderr).toBe(0);return JSON.parse(r.stdout);}finally{await rm(dir,{recursive:true,force:true});}}
test('six levels each have three distinct complete fallback designs; backlog uses the highest stage with at most two extra posts',()=>{
 expect(validate_celebration_wish({wish:'本神愿汝小写token稳驻上下文，Agent童子协作顺遂。'}).wish).toBe('本神愿汝token稳驻上下文，Agent童子协作顺遂。');
 expect(()=>validate_celebration_wish({wish:'本神愿汝token小写到账，已经恢复额度。'})).toThrow();
 expect(points).toEqual([10,50,100,233,500,1000]);expect(prepare_celebration([])).toBeNull();
 for(let tier=0;tier<points.length;tier++){
  const designs=[];for(let v=0;v<3;v++){
   const p=prepare_celebration(points.slice(0,tier+1).map(n=>'集体愿力'+n),v);expect(p.point).toBe(points[tier]);expect(p.name).toBe(names[tier]);expect(p.messages.length).toBe(tier<2?1:2);expect(p.messages.join('\n')).toContain('token');expect(p.messages.join('\n')).not.toContain('（娱乐）');expect(p.messages.every(m=>m.length<2000)).toBe(true);
   const rows=emoji_art(tier,v).split('\n');expect(rows.length).toBe([5,7,9,9,11,13][tier]);expect(new Set(rows.map(r=>Array.from(new Intl.Segmenter('zh',{granularity:'grapheme'}).segment(r)).length)).size).toBe(1);designs.push(p.messages[0]);
  }expect(new Set(designs).size).toBe(3);
 }
});
test('real command execution returns all ceremony parts as one complete CLI result; replay is stable and never calls AI again',async()=>{
 const r=await trial(`await seed(9);let calls=0;globalThis.fetch=async()=>{calls++;throw Error('no network')};const {execute_query}=await import(${JSON.stringify(root+'/src/commands/index.mjs')});const q={command:'pray',args:{action:'offer'}};const opt={context:{...ctx,requestId:'cli'},inputText:'pray --no-ai',humanInput:true,noAi:true};const a=await execute_query(q,opt),b=await execute_query(q,opt);console.log(JSON.stringify({a,b,calls,offers:(await read_state(identity_key)).offers}));`,'wish,festival');
 expect(r.a.text).toContain('**🎆 十炷成阵');expect(r.a.text).toContain('```');expect(r.b.text).toBe(r.a.text);expect(r.calls).toBe(0);expect(r.offers).toBe(10);
});
test('festival AI sees only bounded public ceremony material; one enhancement is saved after counting and used on replay',async()=>{
 const r=await trial(`await seed(9);let bodies=[],committed;globalThis.fetch=async(u,o)=>{const b=JSON.parse(o.body);bodies.push(b);committed=(await read_state(identity_key)).offers;return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({wish:'善信，本神愿汝token绵长，Rust渡劫无惊，CI天灯长明。'})}}]}))};const c={...ctx,requestId:'event'};const opt={festivalDelivery:true,prayerMaterial:'Rust测试不通过 me@example.com'};const a=await pray({action:'offer'},c,opt),b=await pray({action:'offer'},c,opt);console.log(JSON.stringify({a,b,bodies,committed,state:await state()}));`,'festival');
 expect(r.bodies).toHaveLength(1);expect(r.committed).toBe(10);expect(r.a.festivalMessages).toEqual(r.b.festivalMessages);expect(r.a.festivalMessages[0]).toContain('Rust渡劫');expect(r.bodies[0].max_tokens).toBe(240);expect(r.bodies[0].temperature).toBe(1.2);expect(JSON.stringify(r.bodies)).not.toMatch(/private-account|ou_owner|oc_room|fixture-key|me@example.com/);expect(Object.keys(JSON.parse(r.bodies[0].messages[1].content)).sort()).toEqual(['ceremony','material','variant']);expect(r.state.receipts.at(-1).festivalPlan.aiState).toBe('ready');
});
test('festival AI timeout and malformed responses leave complete local art, block only festival after schema failures and never leak errors',async()=>{
 const r=await trial(`let calls=0;globalThis.fetch=async()=>{calls++;return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:'{"wish":"已重置token额度"}'}}]}))};const a=await enrich_celebration(prepare_celebration(['集体愿力10']));const b=await enrich_celebration(prepare_celebration(['集体愿力50']));const c=await enrich_celebration(prepare_celebration(['集体愿力100']));const {ai_status}=await import(${JSON.stringify(root+'/src/ai/runtime.mjs')});const status=await ai_status();console.log(JSON.stringify({calls,a,b,c,status}));`,'festival');
 expect(r.calls).toBe(2);expect(r.status.circuit.features.festival.until).toBeGreaterThan(Date.now());expect(r.status.circuit.provider.until).toBe(0);for(const p of [r.a,r.b,r.c]){expect(p.aiState).toBe('ready');expect(p.messages[0]).toContain('token');expect(p.messages[0]).not.toContain('出了问题');}
 const slow=await trial(`globalThis.fetch=async(u,o)=>new Promise((resolve,reject)=>o.signal.addEventListener('abort',()=>reject(o.signal.reason),{once:true}));const started=Date.now();const p=await enrich_celebration(prepare_celebration(['集体愿力1000']));console.log(JSON.stringify({p,elapsed:Date.now()-started}));`,'festival');expect(slow.elapsed).toBeLessThan(2300);expect(slow.p.messages).toHaveLength(2);
});
test('milestone delivery sends a normal prayer plus two separately receipted markdown posts; repeated resume never duplicates',async()=>{
 const r=await trial(`await seed(99);let bodies=[];const client={send:async b=>{bodies.push(b);return {code:0,data:{message_id:'om_'+bodies.length}}}};const key=delivery_key(ctx.scope,'event');await deliver(client,ctx.scope,'event','pray',null,ctx);await finish_celebration(client,key,ctx);await finish_celebration(client,key,ctx);console.log(JSON.stringify({bodies,ledger:await read_state(key),parts:[await read_state(celebration_key(key,0)),await read_state(celebration_key(key,1))],state:await state(),offers:(await read_state(identity_key)).offers}));`);
 expect(r.bodies).toHaveLength(3);expect(new Set(r.bodies.map(b=>b.uuid)).size).toBe(3);expect(r.bodies.every(b=>b.msg_type==='post')).toBe(true);expect(r.bodies[1].content).toContain('🎆');expect(r.bodies[2].content).toContain('天庭集体战报');expect(r.ledger.festivalFinal).toBe('sent');expect(r.parts.every(p=>p.state==='sent')).toBe(true);expect(r.state.announcedFestivals).toEqual(['集体愿力10','集体愿力50','集体愿力100']);expect(r.offers).toBe(100);
});
test('disk-spool recovery resumes only the missing celebration part and acknowledges after all confirmed sends without recounting',async()=>{
 const r=await trial(`await seed(99);const job={group:ctx.scope,key:'crash',command:'pray',context:ctx,triggerKind:'prayer'};const key=delivery_key(ctx.scope,job.key);const a=await pray({action:'offer'},{...ctx,requestId:key},{noAi:true,festivalDelivery:true});await write_state(key,{state:'sent',group:ctx.scope,festivalRequest:a.festivalRequest,festivalIds:a.festivalIds,festivalMessages:a.festivalMessages});await write_state(celebration_key(key,0),{state:'sent',messageId:'om_already'});await write_pending(job);let bodies=[];const inbox=await create_inbox({send:async b=>{bodies.push(b);return {code:0,data:{message_id:'om_missing'}}}},[ctx.scope]);inbox.resume();for(let i=0;i<300&&inbox.status().pending;i++)await new Promise(r=>setTimeout(r,5));await inbox.stop();console.log(JSON.stringify({bodies,pending:inbox.status().pending,state:await state(),offers:(await read_state(identity_key)).offers}));`);
 expect(r.pending).toBe(0);expect(r.bodies).toHaveLength(1);expect(r.bodies[0].content).toContain('天庭集体战报');expect(r.offers).toBe(100);expect(r.state.festivalClaim).toBeNull();expect(r.state.announcedFestivals).toHaveLength(3);
});
test('known rejection retries only that part with the same UUID; unknown sends never repeat or announce a completed festival',async()=>{
 const r=await trial(`await seed(99);let now=Date.now();Date.now=()=>now;let bodies=[],reject=true;const client={send:async b=>{bodies.push(b);if(bodies.length===3&&reject){reject=false;return {code:999}}return {code:0,data:{message_id:'om_'+bodies.length}}}};const key=delivery_key(ctx.scope,'retry');await deliver(client,ctx.scope,'retry','pray',null,ctx).catch(()=>{});const before=await state();now+=2001;await finish_celebration(client,key,ctx);const recovered=await state();await finish_celebration(client,key,ctx);console.log(JSON.stringify({bodies,before,recovered,offers:(await read_state(identity_key)).offers}));`);
 expect(r.bodies).toHaveLength(4);expect(r.bodies[2].uuid).toBe(r.bodies[3].uuid);expect(r.before.festivalClaim.state).toBe('reserved');expect(r.before.announcedFestivals??[]).toEqual([]);expect(r.recovered.festivalClaim).toBeNull();expect(r.offers).toBe(100);
 const unknown=await trial(`await seed(9);let calls=0;const client={send:async()=>{calls++;if(calls===2)throw Error('unknown');return {code:0,data:{message_id:'om_main'}}}};const key=delivery_key(ctx.scope,'unknown');await deliver(client,ctx.scope,'unknown','pray',null,ctx);await finish_celebration(client,key,ctx);console.log(JSON.stringify({calls,state:await state(),ledger:await read_state(key)}));`);expect(unknown.calls).toBe(2);expect(unknown.ledger.festivalFinal).toBe('uncertain');expect(unknown.state.festivalClaim.state).toBe('uncertain');expect(unknown.state.announcedFestivals??[]).toEqual([]);
});
test('an explicit human pipe receives the complete ceremony instead of losing or leaving side messages untranslated',async()=>{
 const r=await trial(`await seed(99);let input;globalThis.fetch=async(u,o)=>{input=JSON.parse(JSON.parse(o.body).messages[1].content);return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify({text:'全体庆典已读，token祝愿保留。'})}}]}))};const {execute_query}=await import(${JSON.stringify(root+'/src/commands/index.mjs')});const response=await execute_query({command:'pray',args:{action:'offer'},pipeline:[{name:'ask',instruction:'概括这一整场庆典'}]},{humanInput:true,context:{...ctx,requestId:'pipe'},festivalDelivery:true});console.log(JSON.stringify({input,response,offers:(await read_state(identity_key)).offers}));`,'answer');
 expect(JSON.stringify(r.input)).toContain('🎆');expect(JSON.stringify(r.input)).toContain('天庭集体战报');expect(r.response.festivalMessages).toEqual([]);expect(r.response.text).toContain('全体庆典');expect(r.offers).toBe(100);
});
test('rejection budget exhaustion preserves partial-send evidence without replaying the whole celebration',async()=>{
 const r=await trial(`await seed(99);let now=Date.now();Date.now=()=>now;let bodies=[];const client={send:async b=>{bodies.push(b);return bodies.length>2?{code:999}:{code:0,data:{message_id:'om_'+bodies.length}}}};const key=delivery_key(ctx.scope,'budget');await deliver(client,ctx.scope,'budget','pray',null,ctx).catch(()=>{});for(let i=0;i<3;i++){now+=2001;await finish_celebration(client,key,ctx).catch(()=>{})}await finish_celebration(client,key,ctx);console.log(JSON.stringify({bodies,ledger:await read_state(key),part:await read_state(celebration_key(key,1)),state:await state(),offers:(await read_state(identity_key)).offers}));`);
 expect(r.bodies).toHaveLength(5);expect(new Set(r.bodies.slice(2).map(b=>b.uuid)).size).toBe(1);expect(r.part.attempts).toBe(3);expect(r.ledger.festivalFinal).toBe('incomplete');expect(r.state.festivalClaim.state).toBe('uncertain');expect(r.state.announcedFestivals??[]).toEqual([]);expect(r.offers).toBe(100);
});
