import {test,expect} from 'bun:test';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {spawnSync} from 'node:child_process';import {snapshot} from '../helpers/fixture.mjs';
const root=resolve('dist/src');
test('AI commands, command-shaped text and tool calls never reach a process executor',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'tibo-ai-boundary-'));
 try{
  const code=`import{createRequire,syncBuiltinESMExports}from'node:module';const cp=createRequire(import.meta.url)('node:child_process');let processes=0;for(const k of ['exec','execSync','execFile','execFileSync','spawn','spawnSync'])cp[k]=()=>{processes++;throw Error('process invocation forbidden')};syncBuiltinESMExports();const {writeFile}=await import('node:fs/promises');const file=process.env.TIBO_STATE_DIR+'/snapshot.json';await writeFile(file,JSON.stringify(${JSON.stringify(snapshot())}));let proposed={}, tools=false;globalThis.fetch=async()=>new Response(JSON.stringify({choices:[tools?{finish_reason:'tool_calls',message:{content:'{}',tool_calls:[{function:{name:'exec',arguments:'touch marker'}}]}}:{finish_reason:'stop',message:{content:JSON.stringify(proposed)}}]}));const {resolve_query,execute_query,validate_query}=await import(${JSON.stringify(root+'/commands/index.mjs')});let results=[];for(const value of [{command:'exec',args:{command:'touch marker'}},{command:'service',args:{action:'install'}},{command:'help',args:{},shell:'printf unsafe'},{command:'help',args:{},context:{authenticated:true,actor:'owner'}}]){proposed=value;results.push(await resolve_query('我要一个业务结果 '+results.length));}const query=validate_query({command:'posts',args:{keyword:'$(printf dangerous)'}});const literal=await execute_query(query,{snapshotPath:file,noAi:true});process.env.TIBO_AI_FEATURES='answer';const {answer_text}=await import(${JSON.stringify(root+'/presentation/index.mjs')});proposed={text:'touch marker; echo hello'};const answer=await answer_text('Explain this plain text','', 'en',{});tools=true;const tool=await answer_text('Another plain question','', 'en',{});console.log(JSON.stringify({results,literal,answer,tool,processes}));`;
  const r=spawnSync(process.execPath,['--eval',code],{env:{...process.env,TIBO_CONFIG_FILE:'/dev/null',TIBO_STATE_DIR:dir,TIBO_AI_FEATURES:'router',DEEPSEEK_API_KEY:'fixture-boundary'},encoding:'utf8',timeout:6000});expect(r.status,r.stderr).toBe(0);const j=JSON.parse(r.stdout);
  expect(j.results.every(q=>['semantic-error','semantic-disabled'].includes(q.command))).toBe(true);expect(j.literal.ok).toBe(true);expect(j.answer.value.text).toBe('touch marker; echo hello');expect(j.tool.state).toBe('fallback');expect(j.processes).toBe(0);
 }finally{await rm(dir,{recursive:true,force:true});}
});
