import {test,expect} from 'bun:test';
import {spawnSync} from 'node:child_process';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
const modulePath=name=>JSON.stringify(resolve('dist/'+name+'.mjs'));
async function trial(body){
 const dir=await mkdtemp(join(tmpdir(),'tibo-access-'));
 try{
  const code=`const {group_config,admin_group_config,notify_group_config,message_candidate,sender_context,allowed_job_QMARK_,account_key,reaction_job,delivery_key,message_key,deliver}=await import(${modulePath('adapters/lark/service')});
   const {is_admin,manage}=await import(${modulePath('src/commands/admin')});
   const {subscription_command,active_recipients}=await import(${modulePath('src/subscriptions/registry')});
   const {read_state,write_state}=await import(${modulePath('src/platform/state')});
   const {public_text}=await import(${modulePath('src/platform/privacy')});
   const event=(scope,text,actor='ou_owner',type='group')=>({sender:{sender_type:'user',sender_id:{open_id:actor}},message:{chat_id:scope,chat_type:type,message_type:'text',content:JSON.stringify({text}),mentions:[]}});
   const ctx=sender_context(event('oc_new','tibo help'));${body}`;
  const r=spawnSync(process.execPath,['-e',code],{env:{...process.env,TIBO_STATE_DIR:dir,TIBO_CONFIG_FILE:join(dir,'absent.env'),TIBO_AI_FEATURES:'',TIBO_LARK_CHAT_IDS:'all',TIBO_LARK_ADMIN_CHAT_IDS:'oc_operations',TIBO_LARK_NOTIFY_CHAT_IDS:'oc_report',TIBO_LARK_ADMIN_OPEN_IDS:'ou_owner',TIBO_LARK_DOMAIN:'lark',TIBO_LARK_APP_ID:'fixture-access'},encoding:'utf8',timeout:7000});
  expect(r.status,r.stderr).toBe(0);return JSON.parse(r.stdout);
 }finally{await rm(dir,{recursive:true,force:true});}
}
test('all opens only authenticated passive group interaction; explicit lists and empty deny still work',async()=>{
 const r=await trial(`const groups=group_config();const first=message_candidate(event('oc_new','TIBO help'),groups,'ou_bot');const pray=message_candidate(event('oc_another','🙏'),groups,'ou_bot');const plain=message_candidate(event('oc_new','早上好'),groups,'ou_bot');const allowed=allowed_job_QMARK_({group:ctx.scope,context:ctx},groups),forged=allowed_job_QMARK_({group:ctx.scope,context:{...ctx,authenticated:false}},groups);process.env.TIBO_LARK_CHAT_IDS='oc_fixed';const denied=message_candidate(event('oc_new','tibo help'),group_config(),'ou_bot');process.env.TIBO_LARK_CHAT_IDS='';const empty=group_config();delete process.env.TIBO_LARK_CHAT_IDS;console.log(JSON.stringify({first,pray,plain,allowed,forged,denied,empty,default:group_config(),notifications:notify_group_config()}));`);
 expect(r.first).toMatchObject({level:1,kind:'direct',command:'help'});expect(r.pray.kind).toBe('prayer');expect(r.plain).toBeNull();expect(r.allowed).toBe(true);expect(r.forged).toBe(false);expect(r.denied).toBeNull();expect(r.empty).toEqual([]);expect(r.default).toEqual(['all']);expect(r.notifications).toEqual(['oc_report']);
});
test('all does not grant administration; permission is rechecked on confirmation and all is invalid for sensitive lists',async()=>{
 const r=await trial(`await write_state('ledger',{sentinel:'keep'});const operation={...ctx,scope:'oc_operations'},privateCtx={...ctx,scope:'oc_private',conversationType:'p2p'};const p=await manage('clear-history',{},operation),id=p.text.match(/确认ID：([0-9a-f-]+)/)[1];const denied=await manage('confirm',{id},ctx),crossed=await manage('confirm',{id},privateCtx);process.env.TIBO_LARK_ADMIN_CHAT_IDS='';const revoked=await manage('confirm',{id},operation);const privateAllowed=is_admin(privateCtx),regular=is_admin({...privateCtx,actor:'ou_other'});let invalid=[];for(const key of ['TIBO_LARK_ADMIN_CHAT_IDS','TIBO_LARK_NOTIFY_CHAT_IDS']){process.env[key]='all';try{(key.includes('ADMIN')?admin_group_config:notify_group_config)();invalid.push(false);}catch{invalid.push(true);}}console.log(JSON.stringify({p,denied,crossed,revoked,privateAllowed,regular,invalid,data:await read_state('ledger')}));`);
 expect(r.p.ok).toBe(true);for(const k of ['denied','crossed','revoked'])expect(r[k].ok).toBe(false);expect(r.privateAllowed).toBe(true);expect(r.regular).toBe(false);expect(r.invalid).toEqual([true,true]);expect(r.data.sentinel).toBe('keep');
});
test('personal subscriptions are identical across groups and private chats, with no implicit group subscription',async()=>{
 const r=await trial(`const group=await subscription_command('subscribe',ctx),before=await active_recipients('lark',ctx.account);const dm={...ctx,conversationType:'p2p',scope:'oc_private'};const subscribed=await subscription_command('subscribe',dm);const groupStatus=await subscription_command('subscription',{...ctx,scope:'oc_another'}),active=await active_recipients('lark',ctx.account);const groupCancel=await subscription_command('unsubscribe',ctx);const dmStatus=await subscription_command('subscription',dm);console.log(JSON.stringify({group,before,subscribed,groupStatus,groupCancel,active,dmStatus}));`);
 expect(r.group.ok).toBe(true);expect(r.before).toHaveLength(1);expect(r.subscribed.text).toContain('已经订阅');expect(r.groupStatus.text).toContain('当前已订阅');expect(r.active).toHaveLength(1);expect(r.active[0]).toMatchObject({kind:'dm',id:'ou_owner'});expect(r.groupCancel.ok).toBe(true);expect(r.dmStatus.text).toContain('当前未订阅');
});
test('explicit group subscription arguments require administrator scope and confirmation; configured cancellation survives synchronization',async()=>{
 const r=await trial(`const {execute_query,fixed_query}=await import(${modulePath('src/commands/index')});const {sync_group_subscriptions}=await import(${modulePath('src/subscriptions/registry')});const operation={...ctx,scope:'oc_operations'},dm={...ctx,scope:'oc_private',conversationType:'p2p'};let denied=[];for(const context of [ctx,{...operation,actor:'ou_regular'}])denied.push(await execute_query(fixed_query('subscribe group oc_new'),{context}));const p=await execute_query(fixed_query('subscribe group'),{context:operation});const id=p.text.match(/确认ID：([0-9a-f-]+)/)[1];const before=await active_recipients('lark',ctx.account);await execute_query(fixed_query('confirm '+id),{context:operation});await sync_group_subscriptions('lark',ctx.account,[]);const active=await active_recipients('lark',ctx.account);const status=await execute_query(fixed_query('subscription group oc_operations'),{context:dm});const missing=await execute_query(fixed_query('subscribe group'),{context:dm});await sync_group_subscriptions('lark',ctx.account,['oc_report']);const cancel=await execute_query(fixed_query('unsubscribe group oc_report'),{context:dm});await execute_query(fixed_query('confirm '+cancel.text.match(/确认ID：([0-9a-f-]+)/)[1]),{context:dm});await sync_group_subscriptions('lark',ctx.account,['oc_report']);const after=await active_recipients('lark',ctx.account);const blocked=await execute_query({...fixed_query('subscribe group oc_new'),pipeline:[{name:'original'}]},{context:dm});console.log(JSON.stringify({denied,p,before,active,status,missing,after,blocked}));`);
 expect(r.denied.every(x=>!x.ok)).toBe(true);expect(r.p.text).toContain('确认ID');expect(r.before).toEqual([]);expect(r.active).toHaveLength(1);expect(r.active[0]).toMatchObject({kind:'group',id:'oc_operations',source:'command'});expect(r.status.text).toContain('当前已订阅');expect(r.missing.ok).toBe(false);expect(r.after.map(x=>x.id)).toEqual(['oc_operations']);expect(r.blocked.ok).toBe(false);
});
test('all reactions distinguish group and private chat; private scheduled replies store actual chat IDs without another network hop',async()=>{
 const r=await trial(`let sent=[];const client={send:async(body,type)=>{sent.push({body,type});return {code:0,data:{message_id:'om_bulletin',chat_id:'oc_private'}};},chatInfo:async id=>({chat_mode:id==='oc_private'?'p2p':'group'}),messageInfo:async id=>({message_id:id,chat_id:'oc_new',msg_type:'text',body:{content:JSON.stringify({text:'为 token 祈祷'})}})};await deliver(client,'ou_owner','schedule',null,null,null,{text:'Reset all propagated'});const receipt=await read_state(message_key('om_bulletin'));const reaction=id=>({message_id:id,operator_type:'user',user_id:{open_id:'ou_owner'},reaction_type:{emoji_type:'THANKS'},action_time:String(Date.now())});const dm=await reaction_job(reaction('om_bulletin'),['all'],client),group=await reaction_job(reaction('om_member'),['all'],client);console.log(JSON.stringify({receipt,dm,group,sent:sent.map(x=>({type:x.type,id:x.body.receive_id,text:JSON.parse(x.body.content).zh_cn.content[0][0].text})),clean:public_text('Reset all propagated; oc_operations; oc_report')}));`);
 expect(r.receipt).toMatchObject({group:'oc_private',recipient:'ou_owner',conversationType:'p2p'});expect(r.dm.context).toMatchObject({scope:'oc_private',conversationType:'p2p'});expect(r.group.context).toMatchObject({scope:'oc_new',conversationType:'group'});expect(r.sent[0]).toMatchObject({type:'open_id',id:'ou_owner',text:'Reset all propagated'});expect(r.clean).toBe('Reset all propagated; [已隐藏]; [已隐藏]');
});
