import {test,expect} from 'bun:test';
import {mkdtemp,rm} from 'node:fs/promises';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import {spawnSync} from 'node:child_process';
const root=resolve('dist');
async function trial(body){const dir=await mkdtemp(join(tmpdir(),'tibo-prayer-burst-'));try{
 const setup=`let now=Date.parse('2026-10-06T00:00:00Z');Date.now=()=>now;const ctx={transport:'lark',account:'private-account',scope:'oc_room',actor:'ou_owner',authenticated:true,conversationType:'group'};const {pray,record_pray,identity_key,scope_key}=await import(${JSON.stringify(root+'/src/prayer/pray.mjs')});const {read_state,write_state}=await import(${JSON.stringify(root+'/src/platform/state.mjs')});const {process_interaction}=await import(${JSON.stringify(root+'/adapters/lark/interaction.mjs')});const {create_inbox}=await import(${JSON.stringify(root+'/adapters/lark/inbox.mjs')});const {readdir}=await import('node:fs/promises');const pause=ms=>new Promise(r=>setTimeout(r,ms));const until=async fn=>{const end=performance.now()+15000;while(!await fn()){if(performance.now()>end)throw Error('trial timeout');await pause(5)}};`;
 const r=spawnSync(process.execPath,['--eval',setup+body],{env:{...process.env,TIBO_CONFIG_FILE:'/dev/null',TIBO_STATE_DIR:dir,TIBO_AI_FEATURES:'',TIBO_LARK_APP_ID:'fixture',TIBO_LARK_DOMAIN:'lark'},encoding:'utf8',timeout:22000});expect(r.status,r.stderr).toBe(0);return JSON.parse(r.stdout);
 }finally{await rm(dir,{recursive:true,force:true});}}
test('parallel prayers across people and rooms serialize accounting without losing events or changing shared cooldown',async()=>{
 const r=await trial(`const results=await Promise.all(Array.from({length:100},(_,i)=>pray({action:'offer'},{...ctx,actor:'ou_person'+(i%10),scope:'oc_room'+(i%5),requestId:'event'+i},{noAi:true})));const before=await read_state(identity_key);await Promise.all(Array.from({length:100},(_,i)=>pray({action:'offer'},{...ctx,actor:'ou_person'+(i%10),scope:'oc_room'+(i%5),requestId:'event'+i},{noAi:true})));console.log(JSON.stringify({success:results.filter(x=>x.ok).length,before,after:await read_state(identity_key)}));`);
 expect(r.success).toBe(100);expect(r.before.offers).toBe(100);expect(r.before.merit).toBe(10);expect(r.before.members).toHaveLength(10);expect(r.before.scopes).toHaveLength(5);expect(r.after).toEqual(r.before);
 for(const m of r.before.members){expect(m.offers).toBe(10);expect(m.merit).toBe(1);}for(const s of r.before.scopes){expect(s.state.offers).toBe(20);expect(s.state.festivals).toContain('集体愿力10');}
});
test('a suppressed tenth offering unlocks a durable festival; the next permitted response displays it once',async()=>{
 const r=await trial(`let posts=[];const client={send:async b=>{posts.push(JSON.parse(b.content).zh_cn.content[0][0].text);return {code:0,data:{message_id:'om_reply'+posts.length}}}};for(let i=0;i<10;i++)await process_interaction(client,{group:ctx.scope,key:'pray'+i,command:'pray',triggerKind:'prayer',context:ctx});const before=await read_state(identity_key);now+=16001;await Promise.all(['a','b'].map((s,i)=>process_interaction(client,{group:ctx.scope,key:'after'+s,command:'pray',triggerKind:'prayer',context:{...ctx,actor:'ou_after'+i}})));const stats=await pray({action:'stats'},ctx);const after=await read_state(identity_key);const replay=await create_inbox(client,[ctx.scope]);await replay.accept({group:ctx.scope,key:'pray9',command:'pray',triggerKind:'prayer',context:ctx});await pause(20);await replay.stop();console.log(JSON.stringify({posts,before,after,stats,replayed:await read_state(identity_key)}));`);
 expect(r.before.offers).toBe(10);expect(r.before.merit).toBe(1);expect(r.before.scopes[0].state.festivals).toEqual(['集体愿力10']);expect(r.before.scopes[0].state.announcedFestivals??[]).toEqual([]);
 expect(r.posts.filter(x=>x.includes('**🎉 集体彩蛋 · 十炷成阵**'))).toHaveLength(1);expect(r.posts.join('\n')).toContain('🕯️🕯️🕯️🕯️🕯️');expect(r.after.scopes[0].state.announcedFestivals).toEqual(['集体愿力10']);expect(r.after.offers).toBe(12);expect(r.replayed.offers).toBe(12);expect(r.stats.text).toContain('十炷成阵');
});
test('disk inbox accepts a 256-event burst, bounds cached bodies, processes four prayer workers and drains with exact dedup',async()=>{
 const r=await trial(`let release;const gate=new Promise(r=>release=r);let active=0,max=0,sends=0;const client={send:async()=>{active++;max=Math.max(max,active);sends++;await gate;active--;return {code:0,data:{message_id:'om_burst'+sends}}}};const inbox=await create_inbox(client,[ctx.scope]);const jobs=Array.from({length:256},(_,i)=>({group:ctx.scope,key:'burst'+i,command:'pray',triggerKind:'prayer',context:{...ctx,actor:'ou_person'+i%40}}));await Promise.all(jobs.map(j=>inbox.accept(j)));await until(()=>active===4);const queued=inbox.status();release();await until(()=>inbox.status().pending===0);await Promise.all(jobs.map(j=>inbox.accept(j)));await pause(20);await inbox.stop();console.log(JSON.stringify({queued,max,sends,state:await read_state(identity_key),remaining:await readdir(process.env.TIBO_STATE_DIR+'/lark-inbox-pending')}));`);
 expect(r.queued.pending).toBe(256);expect(r.queued.cached).toBeLessThanOrEqual(128);expect(r.max).toBe(4);expect(r.sends).toBe(6);expect(r.state.offers).toBe(256);expect(r.state.merit).toBe(40);expect(r.state.members).toHaveLength(40);expect(r.remaining).toHaveLength(0);
},30000);
test('a fresh inbox recovers the disk spool and a rejected festival send stays pending for the next offering',async()=>{
 const r=await trial(`const {write_pending}=await import(${JSON.stringify(root+'/adapters/lark/inbox-store.mjs')});await Promise.all(Array.from({length:48},(_,i)=>write_pending({group:ctx.scope,key:'restart'+i,command:'pray',triggerKind:'prayer',context:ctx})));let posts=[];const inbox=await create_inbox({send:async b=>{posts.push(JSON.parse(b.content).zh_cn.content[0][0].text);return {code:0,data:{message_id:'om_restart'+posts.length}}}},[ctx.scope]);inbox.resume();await until(()=>inbox.status().pending===0);await inbox.stop();now+=61000;await process_interaction({send:async()=>({code:999})},{group:ctx.scope,key:'rejected',command:'pray',triggerKind:'prayer',context:ctx}).catch(()=>{});const rejected=await read_state(identity_key);now+=16001;await process_interaction({send:async b=>{posts.push(JSON.parse(b.content).zh_cn.content[0][0].text);return {code:0,data:{message_id:'om_good'}}}},{group:ctx.scope,key:'recovered',command:'pray',triggerKind:'prayer',context:ctx});console.log(JSON.stringify({posts,rejected,after:await read_state(identity_key)}));`);
 expect(r.rejected.offers).toBe(49);expect(r.rejected.scopes[0].state.festivalClaim).toBeNull();expect(r.rejected.scopes[0].state.announcedFestivals??[]).toEqual([]);expect(r.posts.at(-1)).toContain('十炷成阵');expect(r.posts.at(-1)).toContain('云端法会');expect(r.after.offers).toBe(50);expect(r.after.scopes[0].state.announcedFestivals).toEqual(['集体愿力10','集体愿力50']);
},30000);
test('reaction acceptance is durable before lookup; transient lookup retries after five minutes and retains original identity',async()=>{
 const r=await trial(`const {pending_reaction}=await import(${JSON.stringify(root+'/adapters/lark/service.mjs')});let reads=0,sends=0;const client={messageInfo:async id=>{reads++;if(reads===1)throw Error('temporary network fault');return {message_id:id,chat_id:ctx.scope,msg_type:'text',body:{content:JSON.stringify({text:'愿CI全绿'})}}},send:async()=>({code:0,data:{message_id:'om_retry'+(++sends)}})};const job=pending_reaction({message_id:'om_source',operator_type:'user',user_id:{open_id:ctx.actor},reaction_type:{emoji_type:'THANKS'},action_time:String(now)},'original-event');let inbox=await create_inbox(client,[ctx.scope]);await inbox.accept(job);const before={reads,pending:inbox.status().pending};await inbox.stop();inbox=await create_inbox(client,[ctx.scope]);inbox.resume();await until(()=>reads===1);await until(async()=>{const files=await readdir(process.env.TIBO_STATE_DIR+'/lark-inbox-pending');const {read_pending}=await import(${JSON.stringify(root+'/adapters/lark/inbox-store.mjs')});return (await read_pending(files[0])).attempts===1});now+=600001;await until(()=>inbox.status().pending===0);await inbox.accept(job);await pause(10);await inbox.stop();console.log(JSON.stringify({before,reads,sends,state:await read_state(identity_key)}));`);
 expect(r.before).toEqual({reads:0,pending:1});expect(r.reads).toBe(2);expect(r.sends).toBe(1);expect(r.state.offers).toBe(1);
},25000);
test('different prayer reaction events on the same message share one metadata lookup and count independently',async()=>{
 const r=await trial(`const {pending_reaction}=await import(${JSON.stringify(root+'/adapters/lark/service.mjs')});let reads=0,sends=0;const client={messageInfo:async id=>{reads++;await pause(15);return {message_id:id,chat_id:ctx.scope,msg_type:'text',body:{content:JSON.stringify({text:'给Agent祝福'})}}},send:async()=>({code:0,data:{message_id:'om_shared'+(++sends)}})};const inbox=await create_inbox(client,[ctx.scope]);const jobs=Array.from({length:24},(_,i)=>pending_reaction({message_id:'om_sharedSource',operator_type:'user',user_id:{open_id:ctx.actor},reaction_type:{emoji_type:'THANKS'},action_time:String(now)},'reaction-event'+i));await Promise.all(jobs.map(j=>inbox.accept(j)));await until(()=>inbox.status().pending===0);await Promise.all(jobs.map(j=>inbox.accept(j)));await until(()=>inbox.status().pending===0);await inbox.stop();console.log(JSON.stringify({reads,sends,state:await read_state(identity_key)}));`);
 expect(r.reads).toBe(1);expect(r.sends).toBe(1);expect(r.state.offers).toBe(24);expect(r.state.merit).toBe(1);
},25000);
test('a full normal cache cannot starve prayers; two normal and four fast network tasks run independently',async()=>{
 const r=await trial(`const {delivery_key}=await import(${JSON.stringify(root+'/adapters/lark/service.mjs')});let release;const gate=new Promise(r=>release=r);const normalIds=new Set(Array.from({length:80},(_,i)=>delivery_key(ctx.scope,'normal'+i).slice(-40)));let normal=0,fast=0,maxNormal=0,maxFast=0,sends=0;const client={send:async b=>{const isNormal=normalIds.has(b.uuid);if(isNormal){normal++;maxNormal=Math.max(maxNormal,normal)}else{fast++;maxFast=Math.max(maxFast,fast)}await gate;if(isNormal)normal--;else fast--;return {code:0,data:{message_id:'om_lane'+(++sends)}}}};const inbox=await create_inbox(client,[ctx.scope]);await Promise.all(Array.from({length:80},(_,i)=>inbox.accept({group:ctx.scope,key:'normal'+i,command:'help | original'})));await until(()=>normal===2);await Promise.all(Array.from({length:4},(_,i)=>inbox.accept({group:ctx.scope,key:'fast'+i,command:'pray',triggerKind:'prayer',context:{...ctx,actor:'ou_fast'+i}})));await until(()=>fast===4);const busy=inbox.status();release();await until(()=>inbox.status().pending===0);await inbox.stop();console.log(JSON.stringify({maxNormal,maxFast,sends,busy,state:await read_state(identity_key)}));`);
 expect(r.maxNormal).toBe(2);expect(r.maxFast).toBe(4);expect(r.busy.workers).toBe(6);expect(r.busy.cached).toBeLessThanOrEqual(128);expect(r.sends).toBe(84);expect(r.state.offers).toBe(4);
},25000);
test('restart after a confirmed send repairs festival acknowledgement without sending or counting again',async()=>{
 const r=await trial(`const {delivery_key}=await import(${JSON.stringify(root+'/adapters/lark/service.mjs')});const {write_pending}=await import(${JSON.stringify(root+'/adapters/lark/inbox-store.mjs')});for(let i=0;i<10;i++)await record_pray({action:'offer'},{...ctx,requestId:'silent'+i},{silent:true});const job={group:ctx.scope,key:'confirmed',command:'pray',triggerKind:'prayer',context:ctx};const key=delivery_key(ctx.scope,job.key);const response=await pray({action:'offer'},{...ctx,requestId:key},{noAi:true,festivalDelivery:true});const before=await read_state(identity_key);await write_state(key,{state:'sent',group:ctx.scope,festivalRequest:response.festivalRequest,festivalIds:response.festivalIds});await write_pending(job);let sends=0;const inbox=await create_inbox({send:async()=>{sends++;throw Error('must not resend')}},[ctx.scope]);inbox.resume();await until(()=>inbox.status().pending===0);await inbox.stop();console.log(JSON.stringify({sends,before,after:await read_state(identity_key)}));`);
 expect(r.before.scopes[0].state.festivalClaim.state).toBe('reserved');expect(r.sends).toBe(0);expect(r.after.offers).toBe(11);expect(r.after.scopes[0].state.festivalClaim).toBeNull();expect(r.after.scopes[0].state.announcedFestivals).toEqual(['集体愿力10']);
});
