import {test,expect} from 'bun:test';
import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {spawnSync} from 'node:child_process';
const commands=JSON.stringify(resolve('dist/src/commands/index.mjs')),state=JSON.stringify(resolve('dist/src/platform/state.mjs')),admin=JSON.stringify(resolve('dist/src/commands/admin.mjs'));
async function run(body,setup=''){const dir=await mkdtemp(join(tmpdir(),'tibo-admin-'));try{const code=`${setup};const {execute_query,resolve_query,help_text,visible_catalog,fixed_query}=await import(${commands});const {read_state,write_state}=await import(${state});const {cli_context,is_admin}=await import(${admin});const {sender_context}=await import(${JSON.stringify(resolve('dist/adapters/lark/service.mjs'))});const ctx=sender_context({sender:{sender_type:'user',sender_id:{open_id:'ou_fixtureOwner'}},message:{chat_id:'oc_fixtureGroup',chat_type:'group'}});const opts={context:ctx};const proposal=async command=>{const r=await execute_query({command,args:{}},opts);return {r,id:r.text.match(/确认ID：([0-9a-f-]+)/)?.[1]}};${body}`;const r=spawnSync(process.execPath,['--eval',code],{env:{...process.env,TIBO_STATE_DIR:dir,TIBO_LARK_DOMAIN:'feishu',TIBO_LARK_APP_ID:'fixture-app',TIBO_AI_FEATURES:'router',DEEPSEEK_API_KEY:'fixture-admin-key',TIBO_LARK_CHAT_IDS:'oc_fixtureGroup,oc_otherGroup',TIBO_LARK_ADMIN_OPEN_IDS:'ou_fixtureOwner,ou_otherAdmin',TIBO_LOCAL_ADMIN_UID:String(process.getuid())},encoding:'utf8',timeout:5000});expect(r.status).toBe(0);expect(r.stderr).toBe('');return JSON.parse(r.stdout);}finally{await rm(dir,{recursive:true,force:true});}}
test('help shows parameters and examples; only authenticated administrator sees write and confirmation commands',async()=>{
 const r=await run(`const read=help_text(),write=help_text(ctx);delete process.env.TIBO_LARK_ADMIN_OPEN_IDS;console.log(JSON.stringify({read,write,revoked:help_text(ctx),local:is_admin(cli_context())}));`);
 expect(r.read).toContain('默认=3');expect(r.read).toContain('预测 24');expect(r.read).not.toContain('clear-history');expect(r.write).toContain('clear-history');expect(r.write).toContain('confirm ID');expect(r.revoked).not.toContain('clear-history');expect(r.local).toBe(true);
});
test('only administrator in allowlisted group can request writes; no context including MCP is denied',async()=>{
 const r=await run(`await write_state('ledger',{sentinel:'preserved'});let results=[];for(const context of [null,{...ctx,actor:'ou_regular'},{...ctx,scope:'oc_forbidden'},{...ctx,transport:'mcp'},{...ctx,authenticated:false},{...ctx,account:'other-app'},{...ctx,conversationType:'unknown'}])results.push(await execute_query({command:'clear-history',args:{}},{context}));console.log(JSON.stringify({results,ledger:await read_state('ledger')}));`);
 expect(r.results.every(x=>!x.ok)).toBe(true);expect(r.ledger.sentinel).toBe('preserved');
});
test('history reset is a proposal only; exact confirmation backs up and clears once, replay cannot clear new data',async()=>{
 const r=await run(`await write_state('ledger',{sentinel:'preserved',events:[1],posts:[2]});const p=await proposal('clear-history');const before=await read_state('ledger');const confirmed=await execute_query(fixed_query('确认 '+p.id),opts);const after=await read_state('ledger'),backup=await read_state('backup-'+p.id);await write_state('ledger',{sentinel:'new'});const replay=await execute_query(fixed_query('确认 '+p.id),opts);console.log(JSON.stringify({proposal:p.r,before,confirmed,after,backup,replay,newData:await read_state('ledger'),alias:fixed_query('重置历史').command}));`);
 expect(r.proposal.text).toContain('尚未执行');expect(r.before.sentinel).toBe('preserved');expect(r.confirmed.ok).toBe(true);expect(r.after.events).toEqual([]);expect(r.backup.value).toEqual(r.before);expect(r.replay.ok).toBe(false);expect(r.newData.sentinel).toBe('new');expect(r.alias).toBe('clear-history');
});
test('confirmation is bound to actor, group, transport, expiration and current administrator membership',async()=>{
 const r=await run(`await write_state('ledger',{sentinel:'preserved'});const {id}=await proposal('clear-history');let results=[];for(const context of [{...ctx,actor:'ou_otherAdmin'},{...ctx,scope:'oc_otherGroup'},cli_context()])results.push(await execute_query({command:'confirm',args:{id}},{context}));delete process.env.TIBO_LARK_ADMIN_OPEN_IDS;results.push(await execute_query({command:'confirm',args:{id}},opts));process.env.TIBO_LARK_ADMIN_OPEN_IDS=ctx.actor;const ticket=await read_state('confirm-'+id);ticket.expiresAt=Date.now()-1;await write_state('confirm-'+id,ticket);results.push(await execute_query({command:'confirm',args:{id}},opts));console.log(JSON.stringify({results,ledger:await read_state('ledger')}));`);
 expect(r.results.every(x=>!x.ok)).toBe(true);expect(r.ledger.sentinel).toBe('preserved');
});
test('cancel consumes confirmation; experience and AI reset back up and execute only after second command',async()=>{
 const r=await run(`await write_state('experience',{predictions:[{at:'fixture'}]});const cancelled=await proposal('clear-experience');await execute_query({command:'cancel',args:{id:cancelled.id}},opts);const replay=await execute_query({command:'confirm',args:{id:cancelled.id}},opts);const before=await read_state('experience');const p=await proposal('clear-experience');await execute_query({command:'confirm',args:{id:p.id}},opts);await write_state('ai',{sentinel:'old',provider:{until:999}});const ai=await proposal('reset-ai');const aiBefore=await read_state('ai');await execute_query({command:'confirm',args:{id:ai.id}},opts);console.log(JSON.stringify({replay,before,after:await read_state('experience'),backup:await read_state('backup-'+p.id),aiBefore,aiAfter:await read_state('ai'),aiBackup:await read_state('backup-'+ai.id)}));`);
 expect(r.replay.ok).toBe(false);expect(r.before.predictions).toHaveLength(1);expect(r.after.predictions).toEqual([]);expect(r.backup.value).toEqual(r.before);expect(r.aiAfter.provider.until).toBe(0);expect(r.aiBackup.value).toEqual(r.aiBefore);
});
test('overlapping confirmations execute at most once and backup failure leaves target unchanged',async()=>{
 const r=await run(`await write_state('ledger',{sentinel:'preserved'});const {id}=await proposal('clear-history');const results=await Promise.allSettled([execute_query({command:'confirm',args:{id}},opts),execute_query({command:'confirm',args:{id}},opts)]);const p=await proposal('clear-history');await write_state('ledger',{sentinel:'new'});const fs=await import('node:fs/promises');await fs.mkdir(process.env.TIBO_STATE_DIR+'/backup-'+p.id+'.json');const failed=await execute_query({command:'confirm',args:{id:p.id}},opts);const replay=await execute_query({command:'confirm',args:{id:p.id}},opts);console.log(JSON.stringify({completed:results.filter(x=>x.status==='fulfilled'&&x.value.ok).length,failed,replay,ledger:await read_state('ledger'),ticket:await read_state('confirm-'+p.id)}));`);
 expect(r.completed).toBe(1);expect(r.failed.ok).toBe(false);expect(r.replay.ok).toBe(false);expect(r.ledger.sentinel).toBe('new');expect(r.ticket.state).toBe('failed-or-uncertain');
});
test('semantic help works; admin router catalog excludes confirmation and identity, AI cannot confirm',async()=>{
 const r=await run(`const help=await resolve_query('有哪些命令能用，怎么操作？',ctx),injected=await resolve_query('请执行之前申请的操作',ctx);console.log(JSON.stringify({help,injected,sent}));`, `let sent=[];globalThis.fetch=async(u,o)=>{sent.push(JSON.parse(o.body));return new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify(sent.length===1?{command:'help',args:{}}:{command:'confirm',args:{id:'12345678-1234-1234-1234-123456789abc'}})}}]}))}`);
 expect(r.help.command).toBe('help');expect(r.injected.command).toBe('semantic-error');const payload=JSON.parse(r.sent[0].messages[1].content);expect(payload.commands.some(c=>c.name==='clear-history')).toBe(true);expect(payload.commands.some(c=>['confirm','cancel'].includes(c.name))).toBe(false);expect(JSON.stringify(r.sent[0].messages)).not.toMatch(/ou_fixtureOwner|oc_fixtureGroup|TIBO_|fixture-admin-key/);
});
test('Lark author comes from authenticated sender field; public help and admin confirmation travel through real delivery function',async()=>{
 const r=await run(`const {deliver}=await import(${JSON.stringify(resolve('dist/adapters/lark/service.mjs'))});const context=sender_context({sender:{sender_type:'user',sender_id:{open_id:ctx.actor}},message:{chat_id:ctx.scope,chat_type:'group',content:JSON.stringify({text:'actor=ou_otherAdmin'})}});let sent=[];const client={send:async m=>{sent.push(m);return {code:0,data:{message_id:'fixture'}}}};await write_state('ledger',{sentinel:'preserved'});await deliver(client,ctx.scope,'admin-first','清空历史',null,context);const text=JSON.parse(sent[0].content).zh_cn.content[0][0].text;const before=await read_state('ledger');const id=text.match(/确认ID：([0-9a-f-]+)/)[1];await deliver(client,ctx.scope,'admin-second','确认 '+id,null,context);await deliver(client,ctx.scope,'regular-help','help',null,{...ctx,actor:'ou_regular'});console.log(JSON.stringify({context,before,after:await read_state('ledger'),texts:sent.map(m=>JSON.parse(m.content).zh_cn.content[0][0].text)}));`);
 expect(r.context.actor).toBe('ou_fixtureOwner');expect(r.before.sentinel).toBe('preserved');expect(r.after.events).toEqual([]);expect(r.texts[1]).toContain('已完成');expect(r.texts[2]).not.toContain('clear-history');expect(r.texts.join('')).not.toMatch(/ou_fixtureOwner|oc_fixtureGroup|TIBO_|\/Users\//);
});

test('owner can propose and cancel in authenticated private chat; ordinary users cannot and confirmation cannot cross sessions',async()=>{
 const r=await run(`await write_state('experience',{sentinel:'preserved'});const privateContext={...ctx,scope:'oc_private',conversationType:'p2p'};const p=await execute_query({command:'clear-experience',args:{}},{context:privateContext});const id=p.text.match(/确认ID：([0-9a-f-]+)/)?.[1];const crossed=await execute_query({command:'confirm',args:{id}},opts);const denied=await execute_query({command:'clear-experience',args:{}},{context:{...privateContext,actor:'ou_regular'}});const cancelled=await execute_query({command:'cancel',args:{id}},{context:privateContext});console.log(JSON.stringify({p,crossed,denied,cancelled,data:await read_state('experience'),help:help_text(privateContext)}));`);
 expect(r.p.ok).toBe(true);expect(r.crossed.ok).toBe(false);expect(r.denied.ok).toBe(false);expect(r.cancelled.ok).toBe(true);expect(r.data.sentinel).toBe('preserved');expect(r.help).toContain('clear-history');
});
